### PR TITLE
[Linux-CIP][v4.4-st14] Merge linux-4.4.y-st backports

### PR DESCRIPTION
**Pull request by bananafunction**
Backports from current linux cip branch (linux-4.4.y-st).
Note: currently no tag is pushed but kernel localversion has already been updated. Therefore this is only a reminder for merge until tag has been pushed upstream :-)

### CODE REVIEW

**Comment by Flamefire** [comment]
I wanted to do a rebase merge to avoid another merge commit. However this currently doesn't work due to b2df16d which conflicts due to an Android change: efc949fedd (as you also found)

I carefully analyzed those 2 as they are very similar:
- The first checks that there is enough room in the target buffer (`transaction`) (fix OOB write)
- The Android change checks that there is enough data in the source buffer (fix OOB read)

So they complement each other. However I noticed the 2nd commit also fixes a potential memory leak by adding `devm_kfree`

In my rebase of your branch I changed b2df16d to cdde800e62, i.e. removed the duplicate `transaction->params_len` assignment. I also noticed that those new checks leak memory and hence added e5bd1072d590

So what about #23 instead? As the CIP guys said the -st will be stable (as opposed to -st-rc) I think we can use that already

**Comment by bananafunction** [comment]
Hi there,

I just pushed further updates from linux-cip/linux-4.4.y-st branch (st14). (Btw: the -st branch is ahead of -st-rc branch (which I find kind of strange -.-)).

I cherry-picked your commit on top of latest merge. We can free the memory, however it is not done on e.g. android-4.9-q branch, so I am not sure if this is just missing/a bug or intended.

Also, I resolved 2 (really) minor conflicts, please see merge commit for information :-)

BR

**Comment by Flamefire** [comment]
> Btw: the -st branch is ahead of -st-rc branch (which I find kind of strange -.-)

Now the -st-rc is ahead of the -st. -.- Guess our best bet is to just take whatever is behind the other and hope that that is stable ;-)

Were you able to test this kernel yet? If so I guess we can merge this now.

**Comment by bananafunction** [comment]
> > Btw: the -st branch is ahead of -st-rc branch (which I find kind of strange -.-)
> 
> Now the -st-rc is ahead of the -st. -.- Guess our best bet is to just take whatever is behind the other and hope that that is stable ;-)
> 
> Were you able to test this kernel yet? If so I guess we can merge this now.

Indeed I wanted to test the changes, but unfortunately my own device is broken (it kissed the pavement hard)... So, the changes are not tested from my side. I put my hope in you 🙂

Btw: shall I keep pushing changes although I won't be able to test them?

**Comment by Flamefire** [comment]
> Btw: shall I keep pushing changes although I won't be able to test them?

I'd guess no. I mean I appreciate your effort especially regarding resolving merge conflicts but as you need to explain those and I need to check them it is likely less effort to directly merge the cip branch myself as I see the conflicts directly then.
Anyway, feel free to open an issue if you see a new CIP tag which I haven't yet. Just to keep track of them.

**Comment by bananafunction** [comment]
Hi @Flamefire ,
fyi: I just reverted your audio coupling fix in favor of a more complete one. Please check it out. I got it from:
 https://github.com/LineageOS/android_kernel_qcom_sdm845/commit/6d6a178f582a801b7e15bec1b61cc7816b35d9d0

Cheers

**Comment by Flamefire** [comment]
Makes sense I guess. Device boots with this change, hence merging

**Pull request merged**
