### PR TITLE
[upstream] Merge 4.4.300, 4.4.301 and 4.4.302 kernel

### PR DESCRIPTION
**Pull request by bananafunction**

### CODE REVIEW

**Comment by bananafunction** [comment]
do not merge for now since pull request currently not tested

**Comment by Flamefire** [comment]
Thanks, going to test this once the LOS Feburary patches are out.

Question already: Is there any benefit in merging each tag? IMO simply merging the 4.4.302 tag is easier/cleaner and already includes  the changes from the prior tags.

**Comment by bananafunction** [comment]
> Thanks, going to test this once the LOS Feburary patches are out.
> 
> Question already: Is there any benefit in merging each tag? IMO simply merging the 4.4.302 tag is easier/cleaner and already includes the changes from the prior tags.

I don't think so. From code base there is no difference, but I think that doing it step by step is actually more acurate when having to solve merge conflicts and naming those depicted files in the merge commit :-) That's all, I guess.

**Comment by bananafunction** [comment]
Btw, when pulling whatawurst changes, I think this pull request can be closed. What do you think?

**Comment by Flamefire** [comment]
> Btw, when pulling whatawurst changes, I think this pull request can be closed. What do you think?

I think I'm gonna merge both, this first. Reason for merging the whatawurst one is to get the metadata up to date to find missed changes etc. But the changeset looks odd, so I'm hesitant merging that without being sure, it doesn't revert any changes or so. So this one first, as it is easy, then check what the other actually changes besides meta-data

**Comment by Flamefire** [comment]
Tested with current LOS sources (February patch level), device boots, wifi, sound, camera is working. USB only roughly checked (adb logcat), but seems to be fine.

Anything in particular which you think is worth checking before merging this?

**Comment by bananafunction** [comment]
> Tested with current LOS sources (February patch level), device boots, wifi, sound, camera is working. USB only roughly checked (adb logcat), but seems to be fine.
> 
> Anything in particular which you think is worth checking before merging this?

That's nice to hear :-)
Checking the list of commits - it may be worth shortly checking BT and writing/reading a file on ext4 partition, but else should be fine.

Thank you for keeping up the work. Btw, upstream 4.4.y kernel reached EOL, so I guess, it might be necessary to backport changes from 4.9.y branch. Anytime soon I'll check if there are new changes as of new CAF tag LA.UM.7.2.r2-11600-8x98.0 :-)

**Comment by Flamefire** [comment]
Transferred an image over BT, so I'd say it works.
etx4 is a bit of an issue: Got a few SELinux denials. But switching to permissive I copied a file to an ext4 SD and was able to read it, even over USB. So I guess that works too.

The audit2allow suggestions for (all) denials are as follows:
```
#============= bluetooth ==============
allow bluetooth gpuservice:binder call;

#============= fsck_untrusted ==============
allow fsck_untrusted media_rw_data_file:dir getattr;
allow fsck_untrusted proc_swaps:file read;

#============= platform_app ==============
allow platform_app sdcard_posix:dir create;
allow platform_app sdcard_posix:file create;

#============= priv_app ==============
allow priv_app property_socket:sock_file write;

#============= system_server ==============
allow system_server sdcard_posix:dir { open read };
```

Full logcat of those: [denials.txt](https://github.com/Flamefire/android_kernel_sony_msm8998/files/8089641/denials.txt)

They look fine to me, so I'd allow them (with the generic macros, see e.g. https://review.gerrithub.io/plugins/gitiles/manfromgta/android_vendor_pac/+/211a90ed19fd381549638b070080b6002e029614/sepolicy/app.te)

Edit: The priv_app has a neverallow rule for exactly that O.o

Edit2:
> Btw, upstream 4.4.y kernel reached EOL, so I guess, it might be necessary to backport changes from 4.9.y branch.

The Sony OpenDevices project uses the 4.14 kernel. Not sure if it is feasible switching to that...   
However we can use the SLTS branch from the CIP: https://git.kernel.org/pub/scm/linux/kernel/git/cip/linux-cip.git/log/?h=linux-4.4.y-cip

**Comment by Flamefire** [comment]
> Anytime soon I'll check if there are new changes as of new CAF tag LA.UM.7.2.r2-11600-8x98.0 :-)

I checked merging the tag `LA.UM.7.2.r2-11600-8x98.0` as per https://github.com/whatawurst/android_kernel_sony_msm8998/pull/45 and haven't found any differences. So it seems it is the same as `LA.UM.7.2.r2-11200-8x98.0` which I merged in January. At least those 3 wifi subtrees. Or did you refer to a tag from https://source.codeaurora.org/quic/la/kernel/msm-4.4 ? At least the tagged commit is already included: https://source.codeaurora.org/quic/la/kernel/msm-4.4/commit/?h=LA.UM.7.2.r2-11600-8x98.0&id=bdae7846485217f54e5983d674577c7ca930fb76

**Comment by Flamefire** [comment]
@bananafunction I do see a quite few errors in the kernel logcat (on a lilac device), any idea if those are important/can be fixed? I haven't noticed any issues in a quick test, but as this is (likely) the kernel it might cause subtle issues later on(?)

Examples:
```
04-11 03:55:53.925     0     0 E msm-thermal soc: qcom,msm-thermal: probe_ocr:Failed reading node=/soc/qcom,msm-thermal, key=qcom,pmic-opt-curr-temp err:-22. KTM continues
04-11 03:55:53.951     0     0 E ipa3_smp2p_probe: 5786 ipa3_ctx was not initialized
04-11 03:55:53.951     0     0 E ipa     : ipa_plat_drv_probe failed

04-11 03:55:53.951     0     0 E ipa_smmu_wlan_cb_probe: 5443 could not alloc iommu domain

04-11 03:55:54.158     0     0 E mdss_mdp_parse_dt_handler: Error from prop qcom,mdss-pipe-sw-reset-off : u32 array read
04-11 03:55:54.158     0     0 E mdss_mdp_parse_dt_handler: Error from prop qcom,mdss-ib-factor-overlap : u32 array read
04-11 03:55:54.158     0     0 E mdss_mdp_parse_dt_handler: Error from prop qcom,mdss-bus-througput-factor : u32 array read
04-11 03:55:54.162     0     0 E mdss_dsi_parse_dcs_cmds: failed, key=qcom,mdss-dsi-timing-switch-command
04-11 03:55:54.162     0     0 E mdss_dsi_parse_dcs_cmds: failed, key=somc,mdss-dsi-pre-uv-command
04-11 03:55:54.163     0     0 E mdss_dsi_parse_dcs_cmds: failed, key=qcom,mdss-dsi-lp-mode-on
04-11 03:55:54.163     0     0 E mdss_dsi_parse_dcs_cmds: failed, key=qcom,mdss-dsi-lp-mode-off
```

[Errors only (filtered)](https://github.com/Flamefire/android_kernel_sony_msm8998/files/8104573/error.log)
[Full log](https://github.com/Flamefire/android_kernel_sony_msm8998/files/8104574/full.log)

**Comment by bananafunction** [comment]
> @bananafunction I do see a quite few errors in the kernel logcat (on a lilac device), any idea if those are important/can be fixed? I haven't noticed any issues in a quick test, but as this is (likely) the kernel it might cause subtle issues later on(?)
> 
> Examples:
> 
> ```
> 04-11 03:55:53.925     0     0 E msm-thermal soc: qcom,msm-thermal: probe_ocr:Failed reading node=/soc/qcom,msm-thermal, key=qcom,pmic-opt-curr-temp err:-22. KTM continues
> 04-11 03:55:53.951     0     0 E ipa3_smp2p_probe: 5786 ipa3_ctx was not initialized
> 04-11 03:55:53.951     0     0 E ipa     : ipa_plat_drv_probe failed
> 
> 04-11 03:55:53.951     0     0 E ipa_smmu_wlan_cb_probe: 5443 could not alloc iommu domain
> 
> 04-11 03:55:54.158     0     0 E mdss_mdp_parse_dt_handler: Error from prop qcom,mdss-pipe-sw-reset-off : u32 array read
> 04-11 03:55:54.158     0     0 E mdss_mdp_parse_dt_handler: Error from prop qcom,mdss-ib-factor-overlap : u32 array read
> 04-11 03:55:54.158     0     0 E mdss_mdp_parse_dt_handler: Error from prop qcom,mdss-bus-througput-factor : u32 array read
> 04-11 03:55:54.162     0     0 E mdss_dsi_parse_dcs_cmds: failed, key=qcom,mdss-dsi-timing-switch-command
> 04-11 03:55:54.162     0     0 E mdss_dsi_parse_dcs_cmds: failed, key=somc,mdss-dsi-pre-uv-command
> 04-11 03:55:54.163     0     0 E mdss_dsi_parse_dcs_cmds: failed, key=qcom,mdss-dsi-lp-mode-on
> 04-11 03:55:54.163     0     0 E mdss_dsi_parse_dcs_cmds: failed, key=qcom,mdss-dsi-lp-mode-off
> ```
> 
> [Errors only (filtered)](https://github.com/Flamefire/android_kernel_sony_msm8998/files/8104573/error.log) [Full log](https://github.com/Flamefire/android_kernel_sony_msm8998/files/8104574/full.log)

I remember that I saw those (or related to msm-thermal and mdss) errors in the kernel logcat in an LOS18.1 build somewhere back in june/july but - just as you said - I didn't recognize any constraints from that so I left it as is.
However, I did not recognize the ipa errors. Maybe one could fix it by correctly initializing ipa3_ctx.

**Comment by Flamefire** [comment]
> I remember that I saw those (or related to msm-thermal and mdss) errors in the kernel logcat in an LOS18.1 build somewhere back in june/july but - just as you said - I didn't recognize any constraints from that so I left it as is. However, I did not recognize the ipa errors. Maybe one could fix it by correctly initializing ipa3_ctx.

There are many more error log entries... :/ But yeah 🤷 

What do you mean exactly by "correctly initializing ipa3_ctx"?

**Pull request merged**
