### PR TITLE
[Linux-CIP][ST1] Merge linux-4.4.y-st backports

### PR DESCRIPTION
**Pull request by bananafunction**
Taken from https://git.kernel.org/pub/scm/linux/kernel/git/cip/linux-cip.git/log/?h=linux-4.4.y-st @ d58deb5cb7f6794eb1d15eb7923fe037c92c0a42

### CODE REVIEW

**Comment by Flamefire** [comment]
Thanks! Do you know what the different branches (and by extension tags) refer to? There is linux-4.4.y-st, linux-4.4.y-cip, linux-4.4.y-cip-rt-rebase, linux-4.4.y-cip-rt, linux-4.4.y-cip-rebase, linux-4.4.y and I haven't found docs about them. My feeling would be that `linux-4.4.y-cip` is the correct one as the "CIP Linux 4.4 kernel" but that doesn't seem to be the case, is it?

Also any reason why you merged from a branch, not a tag? Asking especially as I checked the March ASB and verified that all mentioned kernel patches are either already in the current branch as they are older and/or I included them earlier or they patch issues in features missing in our kernel. So those issues don't exist (yet) and I'm afraid to introduce some.

Having said that those commits sound very reasonable to include. Just want to make sure not to introduce issues or choose the wrong branch leading to merge conflicts later on.

**Comment by bananafunction** [comment]
> Thanks! Do you know what the different branches (and by extension tags) refer to? There is linux-4.4.y-st, linux-4.4.y-cip, linux-4.4.y-cip-rt-rebase, linux-4.4.y-cip-rt, linux-4.4.y-cip-rebase, linux-4.4.y and I haven't found docs about them. My feeling would be that `linux-4.4.y-cip` is the correct one as the "CIP Linux 4.4 kernel" but that doesn't seem to be the case, is it?
> 

Unfortunately, I had the same questions as you. Checking the different branches, to me only "linux-4.4.y-st" and "linux-4.4.y-cip" seemed to be interesting. Then I checked the branch histories and found that all commits from "linux-4.4.y-cip" are included in "linux-4.4.y-st". Also, to me the idea of backporting 4.9.y kernel stuff seemed obvious, so I decided to choose this branch. However, I am not sure what is correct as I cannot find documentation nor I have experience with the CIP, so this is my best guess :-)

> Also any reason why you merged from a branch, not a tag? Asking especially as I checked the March ASB and verified that all mentioned kernel patches are either already in the current branch as they are older and/or I included them earlier or they patch issues in features missing in our kernel. So those issues don't exist (yet) and I'm afraid to introduce some.
> 

I merged from branch since both branches "linux-4.4.y-st" and "linux-4.4.y-cip" do not have a useful (latest greatest) tag to merge (except the 4.4.302 tag we already included from stable). And now, there has been a local version introduced, so let's use it.
Yeah, introducing issues... could happen :-(

> Having said that those commits sound very reasonable to include. Just want to make sure not to introduce issues or choose the wrong branch leading to merge conflicts later on.

Just as said, this is my best guess and since bugs have been found and addressed in stable 4.9.y already, backporting those seem reasonable to me although it might not be necessary when checking March 2022 ASB. But to be honest, all android-4.4-* branches have been deprecated and we can better fix as many stuff as linux-4.9.y reveals.
Another possibility would be just to backport patches mentioned in android-4.9-release branch...

**Comment by Flamefire** [comment]
Found some docs: `-rebase` seem to be only for documentation: Rebase on mainline to highlight changes. So not for us. `-rt` includes the [RPEEMPT_RT patchset](https://www.cip-project.org/blog/2018/03/08/real-time-patchset-for-the-cip-kernel) for realtime devices, so also not for us (realtime requirements lead to more battery consumption)

I'll do some more research and compare the branches, e.g. `USB: serial: cp210x: add CPI Bulk Coin Recycler id` seems to be superflous for us, so maybe `-st` is the `-cip` with updates for hardware support which we don't need.

**Comment by bananafunction** [comment]
> Found some docs: `-rebase` seem to be only for documentation: Rebase on mainline to highlight changes. So not for us. `-rt` includes the [RPEEMPT_RT patchset](https://www.cip-project.org/blog/2018/03/08/real-time-patchset-for-the-cip-kernel) for realtime devices, so also not for us (realtime requirements lead to more battery consumption)
> 
> I'll do some more research and compare the branches, e.g. `USB: serial: cp210x: add CPI Bulk Coin Recycler id` seems to be superflous for us, so maybe `-st` is the `-cip` with updates for hardware support which we don't need.

Actually I don't think that the st branch is only adding more hardware support... E.g. net: fix a memleak ... which ist not yet in cip branch. Let's invest more time in researching :-)

Update: seems to be constantly updated... However, the branch -st was rebased or revoked or Something... Gonna close this PR...

**Comment by Flamefire** [comment]
It seemingly is the other way round: `-st` likely stands for "stable" while `-cip` includes `-st` and adds additional hardware support. See https://irclogs.baserock.org/cip/%23cip.2022-03-18.log.html
So if that wasn't you we are not the only ones wondering about that ;-)

I also compared the -st and -cip history (as of now)  and besides -cip containing a few merges from -st there is only one additional commit: [Merge branch 'linux-4.4.y' into linux-4.4.y-cip](https://git.kernel.org/pub/scm/linux/kernel/git/cip/linux-cip.git/commit/?h=linux-4.4.y-cip&id=33cb6f438d5acbe92fa6aee23ee3e7e5590a9cca)
It has a message of "Merge relevant changes from 4.9.300." which is a bit odd, especially as it comes right before "Merge patches from 4.9.302". However I checked 2 random changes (bugfixes) introduced by that merge and they are also in the -st branch.

In conclusion: Using the `-st` branch seems to be the right way to go. However we may want to wait for tagged releases or risk merge conflicts if they force-push that branch.

We may even introduce issues when tracking the branch: I compared the commits from this PR and the current -st branch: All are equal up to `Merge patches from 4.9.301` being replaced by `Merge patches from 4.9.302` (and followed by more commits). Also 2 commits have been dropped: [cgroup-v1: Require capabilities to set release_agent](https://github.com/Flamefire/android_kernel_sony_msm8998/pull/16/commits/46c33101debfc4226d08933659660a8835b6a0e0) which introduces an unresolved merge conflict and [net: do not keep the dst cache when uncloning an skb dst and its meta](https://github.com/Flamefire/android_kernel_sony_msm8998/pull/16/commits/1a3f7cfb594e6aa55ab32c259bf304b57559cecf) which doesn't seem to affect anything as `CONFIG_DST_CACHE` is seemingly not used/set in our configs.

I asked for clarification on the expected stableness of the branch. As the -st branches seem to be new things may get better.
I'm also wondering what would happen if you merge the current -st branch into yours. I assume it would simply add the new changes but keep the 2 mentioned and now removed commits.
This would mean we'd have to track and check such force-updates manually which is likely unfeasible.

So maybe wait a bit till that clears up and hope we aren't really affected by those issues fixed here. At least none of them are in the March ASB, so I guess we can afford waiting till next month or so.

**Comment by bananafunction** [comment]
> It seemingly is the other way round: `-st` likely stands for "stable" while `-cip` includes `-st` and adds additional hardware support. See https://irclogs.baserock.org/cip/%23cip.2022-03-18.log.html
> So if that wasn't you we are not the only ones wondering about that ;-)
> 

Haha :-) No, it was not me but nice to hear that not only we had understanding problems.

> I also compared the -st and -cip history (as of now)  and besides -cip containing a few merges from -st there is only one additional commit: [Merge branch 'linux-4.4.y' into linux-4.4.y-cip](https://git.kernel.org/pub/scm/linux/kernel/git/cip/linux-cip.git/commit/?h=linux-4.4.y-cip&id=33cb6f438d5acbe92fa6aee23ee3e7e5590a9cca)
> It has a message of "Merge relevant changes from 4.9.300." which is a bit odd, especially as it comes right before "Merge patches from 4.9.302". However I checked 2 random changes (bugfixes) introduced by that merge and they are also in the -st branch.
> 
> In conclusion: Using the `-st` branch seems to be the right way to go. However we may want to wait for tagged releases or risk merge conflicts if they force-push that branch.
> 
> We may even introduce issues when tracking the branch: I compared the commits from this PR and the current -st branch: All are equal up to `Merge patches from 4.9.301` being replaced by `Merge patches from 4.9.302` (and followed by more commits). Also 2 commits have been dropped: [cgroup-v1: Require capabilities to set release_agent](https://github.com/Flamefire/android_kernel_sony_msm8998/pull/16/commits/46c33101debfc4226d08933659660a8835b6a0e0) which introduces an unresolved merge conflict and [net: do not keep the dst cache when uncloning an skb dst and its meta](https://github.com/Flamefire/android_kernel_sony_msm8998/pull/16/commits/1a3f7cfb594e6aa55ab32c259bf304b57559cecf) which doesn't seem to affect anything as `CONFIG_DST_CACHE` is seemingly not used/set in our configs.
> 
> I asked for clarification on the expected stableness of the branch. As the -st branches seem to be new things may get better.
> I'm also wondering what would happen if you merge the current -st branch into yours. I assume it would simply add the new changes but keep the 2 mentioned and now removed commits.
> This would mean we'd have to track and check such force-updates manually which is likely unfeasible.
> 
> So maybe wait a bit till that clears up and hope we aren't really affected by those issues fixed here. At least none of them are in the March ASB, so I guess we can afford waiting till next month or so.

Totally agree, let's wait a bit more until stability is at least detectable ;-). I am gonna merge the latest st branch into my repo and check what will happen...

**Comment by Flamefire** [comment]
Seems they discussed this in the last meeting and created a [new branch](https://git.kernel.org/pub/scm/linux/kernel/git/cip/linux-cip.git/log/?h=linux-4.4.y-st-rc) for development of the stable (i.e. -st) branch. The latter should then be stable. There also is a tag now: [v4.4-st5](https://git.kernel.org/pub/scm/linux/kernel/git/cip/linux-cip.git/tag/?h=v4.4-st5)

Anyway: I think we should be good with only using the tags and go for the branch only in rare situations like CVEs mentioned in the ASB that are fixed in the -st branch but not yet tagged.

**Pull request closed without merging**
